### ISSUE TITLE
Unable to use vmp-resign.py

### ISSUE THREAD

**Issue by re-jim** [castlabs/electron-releases#18]
Windows 10
Python 3.6.5
pip 9.0.3

After doing:
```
pip install cryptography
pip install macholib
pip install file-magic
```

I try to do:
`vmp-resign.py -h `

and I get:

```
\node_modules\electron>vmp-resign.py -h
Traceback (most recent call last):
  File "C:\Users\XXXX\Desktop\Projects\XXXX\XXXX-electron\node_modules\electron\vmp-resign.py", line 16, in <module>
    import magic
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\magic.py", line 23, in <module>
    _libraries['magic'] = _init()
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\magic.py", line 20, in _init
    return ctypes.cdll.LoadLibrary(find_library('magic'))
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python36-32\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python36-32\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
```

And if I do
```
python vmp-resign.py -h
```
I get
```
Traceback (most recent call last):
  File "vmp-resign.py", line 6, in <module>
    from cryptography.hazmat import backends
ImportError: No module named cryptography.hazmat

```
Also, I found a widevine certificate at https://storage.googleapis.com/wvdownload/cert_license_widevine.tgz from widevine's news page: https://www.widevine.com/product_news.html

I see that the tool also takes a "key", which is a required parameter.  What is this key? Can you direct me towards a resource that can help me create one, for developer purposes?

Thanks

**Comment by re-jim** [comment]
Thanks, this workaround works!

I'll see about my python/pip versions and get started on that official cert.
